create table public.loans_current (
  loan_id bigint generated by default as identity,
  loan_amount text,
  loan_lender_tip text,
  loan_reason text,
  loan_due_date text,
  requester_name text,
  requester_score text,
  requester_loans_repaid text,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid not null,
  
  constraint loans_current_pkey primary key (loan_id),
  constraint loans_current_userid_fkey foreign key (user_id) references auth.users (id) on delete cascade
);