create table public.loans_available (
  loan_id bigint generated by default as identity,
  loan_amount text,
  loan_lender_tip text,
  loan_reason text,
  loan_due_date text,
  requester_name text,
  requester_score text,
  requester_loans_repaid text,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  constraint loans_available_pkey primary key (loan_id)
);