--

create table market (
  loan_id bigint generated by default as identity primary key,
  loan_amount text,
  loan_lender_tip text,
  loan_reason text,
  loan_due_date text,
  requester_name text,
  requester_score text,
  requester_loans_repaid text,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);