import Head from 'next/head'
import { useSession } from '@supabase/auth-helpers-react'
import Login from '@/components/auth/Login'
import TodoDisplay from '@/components/todo/TodoDisplay'

export default function Todos() {
  const session = useSession();

  return (
    <>
      <Head>
        <title>Soloscraper 10</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full h-full bg-gray-200">
        
        {!session ? (<Login /> ) : (<TodoDisplay session={session} />)}
      </div>
    </>
  )
}
